#!/bin/bash

adduser --system --no-create-home speedy
mkdir -p /var/log/speedy-notifier
chown speedy /var/log/speedy-notifier
mkdir -p /var/run/speedy-notifier
chown speedy /var/run/speedy-notifier

#DEBHELPER#
