drop type person_status cascade;
drop table person cascade;
drop table skill cascade;
drop table person_skill cascade;
drop type availability_status cascade;
drop table person_day cascade;
drop table area cascade;
drop table project cascade;
drop table project_requirement cascade;
